FROM python:3.12-alpine3.20@sha256:2c6bf2e15946de1c7170a44687ac1c5e140eac87519dfb6c031df6b9ea408470

ENV PYTHONDONTWRITEBYTECODE 1

# Install deps bump
RUN apk add --no-cache build-base libxml2-dev libxslt-dev git nodejs npm g++ make libffi-dev chromium=79.0.3945.130-r0 chromium-chromedriver && rm -rf /var/cache/apk/*

CMD ["/bin/sh"]